config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users

  resources :post_images,only:[:new, :create, :index, :show, :destroy]

  get 'homes/about' => 'homes#about',as: 'about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  has_one_attached :image

  belongs_to :user

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :post_images,dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if: :devise_controller?

  def after_sign_in_path_for(resource)
    post_images_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end
  
  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.save
    redirect_to post_images_path
  end

  def index
    @post_images = PostImage.all
  end

  def show
    @post_image = PostImage.find(params[:id])
  end
  
  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end
  
  
  private
  
  def post_image_params
    params.require(:post_image).permit(:shop_name, :caption)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/homes/about.html.erb
About

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
      <li>
        <%= link_to '投稿フォーム', new_post_image_path %>
      </li>
      
      <li>
        <%= link_to "ログアウト",destroy_user_session_path,method: :delete %>
      </li>
      <% else %>
      <li>
        <%=link_to "新規登録",new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン",new_user_session_path %>
      </li>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/post_images/index.html.erb
<% @post_images.each do |post_image| %>
<div>
 <%= link_to post_image_path(post_image.id) do %>
  <%= image_tag post_image.get_image %>
<% end %>
   <p>投稿ユーザー画像:<%= image_tag 'sample-author1.jpg' %></p>

   <p>ショップ名:<%= post_image.shop_name %></p>

   <p>説明:<%= post_image.caption %></p>

   <p>ユーザーネーム:<%= post_image.user.name %></p>
</div>
<% end %>

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>
 <%= form_with model: @post_image do |f| %>
  <h4>画像</h4>
   <%= f.file_field :image,accept: "image/*" %>
   
  <h4>ショップ名</h4>
   <%= f.text_field :shop_name %>
   
  <h4>説明</h4>
   <%= f.text_area :caption %>
  
  <%= f.submit '投稿' %>
 <% end %>

app/views/post_images/show.html.erb
<div>
  <%= image_tag @post_image.get_image %>
  <p>ショップ名:<%= @post_image.shop_name %></p>

  <p>説明:<%= @post_image.caption %></p>

  <p>投稿ユーザー画像:<%= image_tag 'sample-author1.jpg'</p>

  <p>ユーザーネーム:<%= @post_image.user.name %></p>

  <p>投稿日:<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  
  <% if @post_image.user == current_user %>
   <%= link_to '削除',post_image_path(@post_image),method: :delete %>
  <% end 
  
</div>